### ISSUE TITLE
Alpha map

### ISSUE THREAD

**Issue by mbartlett505** [duckduckgo/tracker-radar-collector#16]

**Comment by mbartlett505** [comment]
![image](https://user-images.githubusercontent.com/57027995/85920073-88279500-b83e-11ea-9fb8-5ea42db0149c.jpeg)

**Comment by kdzwinel** [comment]
some spam qrcode link to otpauth://totp/PayPal:4233135486?secret=OSMA22PE57T4MWXK&issuer=PayPal - user reported
