### ISSUE TITLE
Handle `Network.requestWillBeSentExtraInfo` to capture missed HTTP requests

### ISSUE THREAD

**Issue by gunesacar** [duckduckgo/tracker-radar-collector#20]
In `handleResponseExtraInfo`, tracker-radar-collector sometimes [cannot find a corresponding request](https://github.com/duckduckgo/tracker-radar-collector/blob/98fa0f5a00016a2d10a43d86e16b38601f7ee387/collectors/RequestCollector.js#L215) for a given response. We get logs like the following in such cases:

`google.com: ⚠️ unmatched extra info 1000003503.13`

I found that this happens when `Network.requestWillBeSentExtraInfo` fires before `Network.requestWillBeSent` (or when a request event arrives after the corresponding response event. See, https://github.com/duckduckgo/tracker-radar-collector/issues/21).

Note that [the CDP documentation](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSentExtraInfo) explicitly says:
> there is no guarantee whether requestWillBeSent or requestWillBeSentExtraInfo will be fired first for the same request.

So, handling `requestWillBeSentExtraInfo` event, and keeping a mapping similar to `this._unmatched_extra_info` for the _unmatched_ requests would solve the problem.

Thanks.

**Comment by kdzwinel** [comment]
Thanks a lot for reporting! That's definitely a bug and I'll address it early next week.

#21 seems to be strictly related to this and should be addressed by the same fix, so I'll go ahead and close it.

**Comment by kdzwinel** [comment]
@gunesacar thank you again for reporting. The bug was fixed via #22 . Please let us know if anything still seems off.
