### ISSUE TITLE
waitFor being deprecated by Puppeteer

### ISSUE THREAD

**Issue by SlayterDev** [duckduckgo/tracker-radar-collector#29]
`waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.`

**Comment by kdzwinel** [comment]
Good catch, I took a brief look and it looks like we just have to replace `waitFor` with `waitForTimeout` in one place, but the typescript file for puppeteer doesn't yet have `waitForTimeout` so it'd complain about it and tests would fail. I'll wait with fixing it until we are upgrading puppeteer again.
