### ISSUE TITLE
Collect cookies that only appear on a second page load?

### ISSUE THREAD

**Issue by defunctl** [duckduckgo/tracker-radar-collector#50]
I'm seeing a unique situation where certain cookies are only being set after a reload of the page. Right now there's no way to pass a different browser context via the CLI, I wonder if a flag could be introduced to not set an incognito browser context and then on the second run it would collect the additional cookies?

Or, if you can suggest a better way of collecting certain scripts/cookies that only load once you have already visited a site and visit it again?

Thanks!

**Comment by kdzwinel** [comment]
Sorry for a late response, I missed your message. It's an interesting scenario, we don't have plans right now to allow for reuse of contexts via CLI tool, but you can achieve this by using [Crawler class](https://github.com/duckduckgo/tracker-radar-collector/blob/main/crawler.js) directly where you can pass any context you want. It'd go something like this (not tested code):

```js

const browser = puppeteer.launch(args);
const context = browser.defaultBrowserContext();

// first run
const data = await crawler(new URL('https://example.com'), {
    collectors: [new CookieCollector()],
    browserContext: context
});

// second run
const data2 = await crawler(new URL('https://example.com'), {
    collectors: [new CookieCollector()],
    browserContext: context
});
```

LMK if you have any follow up questions.

**Comment by kdzwinel** [comment]
Closing since there were no follow up questions, feel free to reopen if needed!
