### ISSUE TITLE
Navigator property access detection is flaky on certain pages

### ISSUE THREAD

**Issue by gunesacar** [duckduckgo/tracker-radar-collector#6]
First, thanks so much building this amazing tool.

We found that tracker-radar-collector is missing some navigator property accesses while testing it on the browser fingerprinting demo page https://browserleaks.com/.

To reproduce, run:
`npm run crawl  -- -u "https://browserleaks.com/javascript" -d 'apis'  -o ./data/ -v`
The list of detected API calls should contain, for instance, access to `Navigator.prototype.hardwareConcurrency`, while it doesn't.

To verify that a script on that page collects `hardwareConcurrency`, visit the [site](https://browserleaks.com/javascript) and you'll see it printed as part of your fingerprint. You can also manually debug https://browserleaks.com/js/javascript.js?v=14554822 to verify the collection.

We then wanted to find out whether `hardwareConcurrency` is consistently missed by the tracker-radar-collector or not. tracker-radar-collector could successfully capture access to this property on other sites such as https://google.com or on a [test page](https://jsfiddle.net/8cfxgubj/) that we set up.

We then tried to find out whether the failure to capture has something to do with the access notation. i.e., `navigator.hardwareConcurrency` vs. `navigator['hardwareConcurrency']`. But, tracker-radar-collector could successfully detect property accesses using both notations on a [test page](https://jsfiddle.net/8cfxgubj/) that we setup.

Other things we've tried to dissect the issue without any luck:
- running the command above in a loop, ten times
- increasing the `EXECUTION_WAIT_TIME` to 10,000

PS: `hardwareConcurrency` is just an example; it's not the only property that is accessed and missed by the tracker-radar-collector on that site.

Tests were run on Windows and Linux, using the latest master from the repo. Other SW versions:
- Chromium version (used the by the tracker-radar-collector): `78.0.3882.0 (Developer Build) (64-bit)`
- Node version: v14.4.0

(@asumansenol contributed to this report)

**Comment by kdzwinel** [comment]
Hey Gunes and Asuman👋 Thank you both for taking time to report this bug, we really appreciate it.

I inspected the problem and you are right, some data is not being correctly collected. After some digging I found out there appears to be short period of time at the very beginning of the page load when some API calls are not being collected. As far as I can tell I managed to close that gap with #7, but please let us know if something is still off!

One other issue that I observed is that `speechSynthesis.getVoices()` is not correctly detected, but the issue here seems to be unrelated, so I moved it to #8.

**Comment by gunesacar** [comment]
Hey Konrad,

Pulled your branch and verified the fix. All API calls were captured.

Just to test for flakiness, I tested the site in question in a loop, ten times. API calls were consistently detected.

Thanks so much for the prompt fix.

**Comment by kdzwinel** [comment]
@gunesacar thank you for verifying! We are exited to see privacy researches interested in our tools, so please let us know if there is anything we can help with.

**Comment by gunesacar** [comment]
Excellent. Will do.
